"""empty message

Revision ID: aaca580d959f
Revises: 072fda1a5049
Create Date: 2026-04-29 11:09:10.814454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaca580d959f'
down_revision = '072fda1a5049'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assistant_agent_conversation_id', sa.UUID(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_column('assistant_agent_conversation_id')

    # ### end Alembic commands ###
