"""add usage_record table

Revision ID: b3e1f7a29c41
Revises: f7f74a3c4490
Create Date: 2026-09-10 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'b3e1f7a29c41'
down_revision = 'f7f74a3c4490'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage_record',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('app_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False),
    sa.Column('provider_name', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False),
    sa.Column('model_name', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('raw_usage', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_usage_record_id')
    )
    with op.batch_alter_table('usage_record', schema=None) as batch_op:
        batch_op.create_index('usage_record_account_id_idx', ['account_id'], unique=False)
        batch_op.create_index('usage_record_app_id_idx', ['app_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usage_record', schema=None) as batch_op:
        batch_op.drop_index('usage_record_app_id_idx')
        batch_op.drop_index('usage_record_account_id_idx')

    op.drop_table('usage_record')
    # ### end Alembic commands ###
